### ISSUE TITLE
golang support?

### ISSUE THREAD

**Issue by Explorer1092** [rapid7/metasploit-payloads#290]

**Comment by bwatters-r7** [comment]
PRs accepted.

**Comment by OJ** [comment]
I'm not sure I understand what this even means. Is the internet here
suggesting a rewrite using Go instead of C? Or having a version work
completely in Go?

If so... Nope! No need for another version that compiles to a native
binary. It'd make more sense to use something that lives in other runtimes,
such as a .NET version.

If not then we do support Golang. Just inject into a running program
written in Go 😁
