### ISSUE TITLE
Juicy Potato

### ISSUE THREAD

**Issue by SimonGurney** [rapid7/metasploit-payloads#375]
Juicy Potato is a reliable elevation to system from an exploited IIS or Sql instance.  The payload is already available in MSF but could it be incorporated into the meterpreter "get system" command where impersonation privileges are available?  Given that MS have advised it cannot be patched, it seems an excellent candidate.

**Comment by smcintyre-r7** [comment]
Since there already is an exploit module for it like you mentioned, I don't really think it's worth the effort to incorporate it into `getsystem`.  Also according to our module [docs](https://github.com/rapid7/metasploit-framework/blob/c0b42ff7a2a1b677aaba6acd7ebeefddcffdf38e/documentation/modules/exploit/windows/local/ms16_075_reflection_juicy.md#vulnerable-applications) the issue was fixed in Windows 10 v1809. The `getsystem` functionality definitely shouldn't be including exploits any more, there was an effort a while ago to remove traditional exploits from it in favor of using modules which are better suited for the task of exploiting vulnerabiliites (they have things like user-configurable options and more robust output capabilities).
