### ISSUE TITLE
suggestion: meterpreter, lazagne extension. This will may replace many modules in meterpreter.

### ISSUE THREAD

**Issue by Narutto2011** [rapid7/metasploit-payloads#410]
https://github.com/AlessandroZ/LaZagne

**Comment by bcoles** [comment]
A lot of these checks are already implemented in Metasploit.

A similar project was attempted previously (https://github.com/rapid7/metasploit-framework/pull/11998, https://github.com/rapid7/metasploit-framework/pull/11719), but it was ultimately decided that the functionality would make more sense as separate modules rather than a single module (https://github.com/rapid7/metasploit-framework/issues/13284).

If there are specific checks you think would be useful, that aren't already mentioned [here](https://github.com/rapid7/metasploit-framework/issues/13284), please create a new issue on the Metasploit Framework repository (rather than Metasploit Payloads).
