### ISSUE TITLE
Python meterpreter treats cmd_exec differently than executable meterpreter

### ISSUE THREAD

**Issue by bwatters-r7** [rapid7/metasploit-payloads#512]
While working on https://github.com/rapid7/metasploit-framework/pull/15822
I noticed that cmd_exec behaves differently when run in Python meterpreter and Mettle.  Specifically, cmd_exec should take four arguments:
`lib/msf/core/post/common.rb:  def cmd_exec(cmd, args=nil, time_out=15, opts = {})`
You can verify this behavior by getting a python meterpreter session and a binary meterpreter session, setting it to a post module and running:
`cmd_exec('ls -larth')`
`cmd_exec('ls', '-larth')`
In theory, these should be the same, but they are not.  In Mettle (and Windows executable meterpreter, I believe) the output matches, but in Python meterpreter, the args are ignored.

**Comment by timwr** [comment]
So I think the issue is on python, the arguments get appended to /bin/sh
https://github.com/rapid7/metasploit-payloads/blob/d08b1b31e86dcab042ea61e1098e9b7881863c66/python/meterpreter/ext_server_stdapi.py#L1166

Whereas on mettle, they concatenated into one final argument for /bin/sh, e.g:
https://github.com/rapid7/mettle/blob/6fffb8a945bea1391567cdcfcad80371f73ca520/mettle/src/process.c#L205

```
Python:
cmd_exec('echo test') calls:
[*] starting process: ['/bin/sh', '-c', 'echo test', '']

cmd_exec('echo', 'test') calls:
[*] starting process: ['/bin/sh', '-c', 'echo', 'test']

Mettle: 
cmd_exec('echo test') calls:
[pid 18453] execve("/bin/sh", ["/bin/sh", "-c", "echo test "], 0xb1dca0 /* 4 vars */) = 0

cmd_exec('echo', 'test') calls:
[pid 18452] execve("/bin/sh", ["/bin/sh", "-c", "echo test"], 0xb1dca0 /* 4 vars */) = 0
```

Probably the simplest fix is to ensure the python meterpreter concatenates the arguments with the cmd (only when PROCESS_EXECUTE_FLAG_SUBSHELL is set).
We could consider adding something in the cmd_exec tests for this case too.
