### ISSUE TITLE
'Beacon' Style Mode: Any plans work on something like this?

### ISSUE THREAD

**Issue by realoriginal** [rapid7/metasploit-payloads#618]
Good Afternoon,

Curious, is there any plans to develop a Beacon style mode for MSF? I'd love to help with that on the payload side if there is some interest.

**Comment by gwillcox-r7** [comment]
@realoriginal Can you expand on what specific features you are looking for here? Jitter support? Ability to communicate over different protocols? More specifics would be required to give you an idea on how to implement this. Whilst I believe there has been some discussion in the past of this my understanding was that as the payloads are coded atm, introducing something like Jitter where the connection would be expected to drop and then continue later on would require a significant reworking of the way our payloads work at the moment. Because of this, it would likely be considered a breaking change that would need to go out in a major release vs a point release.

As it stands right now I'm not aware of any plans to implement a beacon style mode into our payloads.

I'd flesh out what you'd be interested in here some more and then the team can provide some feedback on these ideas so we can find a solution that works for everyone. I think this is a good idea just concerned that there may be some considerations from the team that would need to be taken into account if this were to be implemented.
