### ISSUE TITLE
Docker mingw build doesn't work from mac host

### ISSUE THREAD

**Issue by adfoster-r7** [rapid7/metasploit-payloads#641]
The docker mingw build doesn't work from a mac host. It also doesn't work when using vmware shared folder running from macosx, and building on a ubuntu host machine either.

Failure:

```
/usr/share/mingw-w64/include/ntstatus.h:582: note: this is the location of the previous definition
  582 | #define STATUS_LOGON_TYPE_NOT_GRANTED ((NTSTATUS)0xC000015B)
      |
In file included from /meterpreter/source/extensions/kiwi/mimikatz/modules/rpc/kull_m_rpc.h:19,
                 from /meterpreter/source/extensions/kiwi/mimikatz/modules/rpc/kull_m_rpc_ms-efsr.h:7,
                 from /meterpreter/source/extensions/kiwi/mimikatz/modules/rpc/kull_m_rpc_ms-efsr_c.c:6:
/meterpreter/workspace/ext_server_priv/../../source/extensions/kiwi/mimikatz/inc/midles.h:124:5: error: unknown type name '__deref_in_bcount_opt'; did you mean 'SAL__deref_in_bcount_opt'?
  124 |     __deref_in_bcount_opt(BufferSize) char **pBuffer,
      |     ^~~~~~~~~~~~~~~~~~~~~
      |     SAL__deref_in_bcount_opt
make[3]: *** [ext_server_priv/CMakeFiles/ext_server_priv.dir/build.make:64: ext_server_priv/CMakeFiles/ext_server_priv.dir/meterpreter/source/extensions/kiwi/mimikatz/modules/rpc/kull_m_rpc_ms-efsr_c.c.obj] Error 1
make[3]: Leaving directory '/meterpreter/workspace/build/mingw-x86'
make[2]: *** [CMakeFiles/Makefile2:427: ext_server_priv/CMakeFiles/ext_server_priv.dir/all] Error 2
make[2]: Leaving directory '/meterpreter/workspace/build/mingw-x86'
make[1]: *** [Makefile:84: all] Error 2
make[1]: Leaving directory '/meterpreter/workspace/build/mingw-x86'
make: *** [Makefile:29: meterpreter-x86-build] Error 2
make: *** [docker] Error 2
➜  meterpreter git:(build-mingw-build-on-github-actions)

```

It looks like compiling works in the container just fine, as long as the mounted volume isn't used:

```
docker run -u jenkins -it  -v ${PWD}:/meterpreter -w /meterpreter rapid7/msf-ubuntu-x64-meterpreter:latest /bin/bash --login
```

i.e. moving into `/tmp/meterpreter` and git cloning/git init submodules/etc, works - but the mounted `/meterpreter` fails. Potentially something to do with permissions/uids/gids, or different file traversal order (?), not sure yet - haven't looked deeper.

**Comment by adfoster-r7** [comment]
Looks like both @sjanusz-r7 and @cdelafuente-r7 have bumped into this

It might be worth taking a deeper look into why this is breaking; I'm pretty sure it's uid/gid issues or file traversal order differences

**Comment by adfoster-r7** [comment]
@cdelafuente-r7 I think you've fixed this now? 👀

**Comment by cdelafuente-r7** [comment]
Yes, I was able to build with some addition to these files:
https://github.com/rapid7/metasploit-payloads/blob/7ff8ee535f2d29c39c8d176d2d5a7baad1889c06/c/meterpreter/workspace/ext_server_kiwi/CMakeLists.txt#L49-L52
https://github.com/rapid7/metasploit-payloads/blob/7ff8ee535f2d29c39c8d176d2d5a7baad1889c06/c/meterpreter/workspace/ext_server_priv/CMakeLists.txt#L45-L48

These changes were required due to a change in Mingw definitions ([here](https://github.com/mirror/mingw-w64/commit/c643b82daca9985d0ed1f20631e59abdee02b793) and [here](https://github.com/mirror/mingw-w64/commit/0356d967025ba74c26e574e4f1211e0ff8ec0708)).

That said, it sounds weird, since without this fix, it should break on other platforms too. I have no idea why it was only breaking on Mac OSX.

**Comment by adfoster-r7** [comment]
Thanks! Will close
