### ISSUE TITLE
There was a problem parsing the package, showing while installing the msfvenom payload in redmi 8 dual phone. How to fix this issue !

### ISSUE THREAD

**Issue by dhil-dhin** [rapid7/metasploit-payloads#692]
![IMG_20240102_061839_573](https://github.com/rapid7/metasploit-payloads/assets/155403235/04561d69-e4b3-494d-9e7f-34b482d60e6f)

**Comment by Morsmalleo** [comment]
Your problem comes from your msfvenom payload not being zipaligned.

I recommend you use either the [Uber APK SIgner](https://GitHub.com/patrickfav/Uber-APK-Signer) CLI app to zipalign and sign your APK with one command, or you can use [APKEasyTool](https://apk-easy-tool.en.lo4d.com/windows) to zipalign and sign your APK using a GUI (Graphical User Interface)

**Comment by h00die** [comment]
Possibly related to https://github.com/rapid7/metasploit-framework/issues/19154
